app/models/user.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db


# モデルに関する設定
class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1000))
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))

    # モデルからインスタンスを生成するときに使います。(利便性を高めるため)
    # passwordの暗号化も自動で行うことができるので、安全性も高めることができます。
    @classmethod
    def from_args(cls, name: str, email: str, password: str):
        instance = cls()
        instance.name = name
        instance.email = email
        instance.email = email
        if password is not None:
            # passwordがあれば暗号化します。
            instance.hash_password(password)
        return instance

    # 暗号化するためのメソッド。
    def hash_password(self, clean_password):
        self.password = generate_password_hash(str(clean_password), method='sha256')

    # 登録したpasswordとユーザーがログインフォームで入力したパスワードが正しいかどうかのチェックを行うメソッド
    def check_password(self, clean_password):
        return check_password_hash(self.password, clean_password)

app/__init__.py
# モジュールインポート
from flask import Flask, render_template
# データベースを利用するために追加
from flask_sqlalchemy import SQLAlchemy
# flaks-loginのライブラリ追加
from flask_login import LoginManager, login_required

# Flaskアプリの生成
app = Flask(__name__)

# ここから /// データベースの設定
app.secret_key = "super secret key"
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///qa-site.sqlite3'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
# ここまで /// データベースの設定

# sqlalchemyを通してflaskからdbアクセスをするための入り口
db = SQLAlchemy(app)

# flask-loginに関する設定
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

# データベースのimport
from app.models.user import User


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


# authに関するルーティングを追加
from app.views.auth import auth

# authに関するルートをflaskアプリであるappに追加
app.register_blueprint(auth)


# indexのルート設定
@app.route('/')
@login_required  # ここを追加
def index():
    return render_template('index.html')

app/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required

from app.services import auth_service

auth = Blueprint('auth', __name__)


# signupページと、postするページを共通化。
@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'GET':
        return render_template('auth/signup.html')
    else:
        user = auth_service.signup(request.form)
        if user:
            flash('メールアドレスは既に登録されています。')
            return redirect(url_for('index'))
        flash('新規登録に成功しました。')
        return redirect(url_for('index'))


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('auth/login.html')
    else:
        user = auth_service.login(request.form)
        if not user:
            flash('メールアドレスもしくはパスワードに誤りがあります。')
            return render_template('auth.login')
        flash('ログインしました。')
        return redirect(url_for('index'))


@auth.route('/logout')
@login_required
def logout():
    auth_service.logout()
    flash('ログアウトしました。')
    return redirect(url_for('auth.login'))

app/templates/index.html
{% extends "layout.html" %}

{% block content %}
    <h1>
        Index page
    </h1>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>QA-Site</title>
</head>

<body>
<ul>
    {# ログインしていれば表示 #}
    {% if  current_user.is_authenticated %}
        <li><a href="{{ url_for('index') }}">Index</a></li>
        <li><a href="{{ url_for('auth.logout') }}">ログアウト</a></li>
    {% endif %}

    {#ログインしていなければ表示#}
    {% if not current_user.is_authenticated %}
        <li><a href="{{ url_for('auth.signup') }}">新規登録</a></li>
        <li><a href="{{ url_for('auth.login') }}">ログイン</a></li>
    {% endif %}
</ul>
{# flaskのメッセージを表示 #}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <div>
            {{ messages[0] }}
        </div>
    {% endif %}
{% endwith %}
{% block content %}
{% endblock %}


</body>

</html>